2024-11-19 10:13:06,350 - INFO - pikepdf C++ to Python logger bridge initialized
2024-11-19 10:15:19,257 - INFO - pikepdf C++ to Python logger bridge initialized
2024-11-19 10:16:32,847 - INFO - pikepdf C++ to Python logger bridge initialized
2024-11-19 10:17:43,218 - INFO - pikepdf C++ to Python logger bridge initialized
2024-11-19 10:18:30,669 - INFO - pikepdf C++ to Python logger bridge initialized
2024-11-19 10:18:38,159 - WARNING - Not Found: /favicon.ico
2024-11-19 10:20:53,474 - INFO - D:\TTCSCN_NHOM38\backend\WEBPDF\webpdf\pdfdata\urls.py changed, reloading.
2024-11-19 10:20:54,388 - INFO - pikepdf C++ to Python logger bridge initialized
2024-11-19 10:21:01,401 - INFO - D:\TTCSCN_NHOM38\backend\WEBPDF\webpdf\pdfdata\urls.py changed, reloading.
2024-11-19 10:21:10,870 - INFO - D:\TTCSCN_NHOM38\backend\WEBPDF\webpdf\pdfdata\urls.py changed, reloading.
2024-11-19 10:21:11,671 - INFO - pikepdf C++ to Python logger bridge initialized
2024-11-19 10:21:13,404 - INFO - D:\TTCSCN_NHOM38\backend\WEBPDF\webpdf\pdfdata\urls.py changed, reloading.
2024-11-19 10:21:14,201 - INFO - pikepdf C++ to Python logger bridge initialized
2024-11-19 10:21:15,931 - INFO - D:\TTCSCN_NHOM38\backend\WEBPDF\webpdf\pdfdata\urls.py changed, reloading.
2024-11-19 10:21:16,756 - INFO - pikepdf C++ to Python logger bridge initialized
2024-11-19 10:21:50,344 - ERROR - Internal Server Error: /pdfdata/
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\TTCSCN_NHOM38\backend\WEBPDF\webpdf\pdfdata\views.py", line 10, in pdfdata
    return render(request, 'pdfdata/pdfdata.html')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
2024-11-19 10:22:07,423 - WARNING - Method Not Allowed: /pdfdata/down/
2024-11-19 10:22:59,928 - WARNING - Forbidden (CSRF cookie not set.): /pdfdata/down/
2024-11-19 10:24:28,810 - WARNING - Forbidden (CSRF cookie not set.): /pdfdata/down/
2024-11-19 10:26:14,205 - INFO - D:\TTCSCN_NHOM38\backend\WEBPDF\webpdf\pdfdata\views.py changed, reloading.
2024-11-19 10:27:18,642 - INFO - pikepdf C++ to Python logger bridge initialized
2024-11-19 10:27:28,525 - ERROR - L\u1ed7i khi \u0111\u0103ng nh\u1eadp: HTTPSConnectionPool(host='backend8181.bcy.gov.vn', port=443): Max retries exceeded with url: /api/users/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001989E60F5B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2024-11-19 10:27:28,525 - CRITICAL - L\u1ed7i không xác \u0111\u1ecbnh: HTTPSConnectionPool(host='backend8181.bcy.gov.vn', port=443): Max retries exceeded with url: /api/users/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001989E60F5B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2024-11-19 10:27:28,525 - ERROR - Internal Server Error: /pdfdata/down/
2024-11-19 10:28:47,178 - ERROR - L\u1ed7i khi \u0111\u0103ng nh\u1eadp: 400 Client Error:  for url: https://backend8181.bcy.gov.vn/api/users/login
2024-11-19 10:28:47,178 - CRITICAL - L\u1ed7i không xác \u0111\u1ecbnh: 400 Client Error:  for url: https://backend8181.bcy.gov.vn/api/users/login
2024-11-19 10:28:47,179 - ERROR - Internal Server Error: /pdfdata/down/
2024-11-19 10:29:28,940 - ERROR - L\u1ed7i khi \u0111\u0103ng nh\u1eadp: 400 Client Error:  for url: https://backend8181.bcy.gov.vn/api/users/login
2024-11-19 10:29:28,941 - CRITICAL - L\u1ed7i không xác \u0111\u1ecbnh: 400 Client Error:  for url: https://backend8181.bcy.gov.vn/api/users/login
2024-11-19 10:29:28,941 - ERROR - Internal Server Error: /pdfdata/down/
2024-11-19 10:30:39,433 - ERROR - L\u1ed7i khi \u0111\u0103ng nh\u1eadp: 400 Client Error:  for url: https://backend8181.bcy.gov.vn/api/users/login
2024-11-19 10:30:39,434 - CRITICAL - L\u1ed7i không xác \u0111\u1ecbnh: 400 Client Error:  for url: https://backend8181.bcy.gov.vn/api/users/login
2024-11-19 10:30:39,434 - ERROR - Internal Server Error: /pdfdata/down/
2024-11-19 10:31:57,288 - ERROR - L\u1ed7i khi \u0111\u0103ng nh\u1eadp: 400 Client Error:  for url: https://backend8181.bcy.gov.vn/api/users/login
2024-11-19 10:31:57,288 - CRITICAL - L\u1ed7i không xác \u0111\u1ecbnh: 400 Client Error:  for url: https://backend8181.bcy.gov.vn/api/users/login
2024-11-19 10:31:57,288 - ERROR - Internal Server Error: /pdfdata/down/
2024-11-19 10:32:18,165 - INFO - D:\TTCSCN_NHOM38\backend\WEBPDF\webpdf\pdfdata\views.py changed, reloading.
2024-11-19 10:32:19,056 - INFO - pikepdf C++ to Python logger bridge initialized
2024-11-19 10:32:22,548 - ERROR - L\u1ed7i khi \u0111\u0103ng nh\u1eadp: 400 Client Error:  for url: https://backend8181.bcy.gov.vn/api/users/login
2024-11-19 10:32:22,548 - CRITICAL - L\u1ed7i không xác \u0111\u1ecbnh: 400 Client Error:  for url: https://backend8181.bcy.gov.vn/api/users/login
2024-11-19 10:32:22,548 - ERROR - Internal Server Error: /pdfdata/down/
2024-11-19 10:34:22,094 - ERROR - L\u1ed7i khi \u0111\u0103ng nh\u1eadp: 400 Client Error:  for url: https://backend8181.bcy.gov.vn/api/users/login
2024-11-19 10:34:22,094 - CRITICAL - L\u1ed7i không xác \u0111\u1ecbnh: 400 Client Error:  for url: https://backend8181.bcy.gov.vn/api/users/login
2024-11-19 10:34:22,094 - ERROR - Internal Server Error: /pdfdata/down/
2024-11-19 10:34:47,589 - INFO - D:\TTCSCN_NHOM38\backend\WEBPDF\webpdf\pdfdata\views.py changed, reloading.
2024-11-19 10:35:00,846 - INFO - pikepdf C++ to Python logger bridge initialized
2024-11-19 10:39:04,358 - INFO - D:\TTCSCN_NHOM38\backend\WEBPDF\webpdf\pdfdata\views.py changed, reloading.
2024-11-19 10:39:05,308 - ERROR - L\u1ed7i khi \u0111\u0103ng nh\u1eadp: HTTPSConnectionPool(host='backend8181.bcy.gov.vn', port=443): Max retries exceeded with url: /api/users/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002D2B4DB98D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2024-11-19 10:39:05,314 - ERROR - L\u1ed7i khi \u0111\u0103ng nh\u1eadp: HTTPSConnectionPool(host='backend8181.bcy.gov.vn', port=443): Max retries exceeded with url: /api/users/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002D2B4DBB070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2024-11-19 10:40:29,854 - ERROR - L\u1ed7i khi \u0111\u0103ng nh\u1eadp: HTTPSConnectionPool(host='backend8181.bcy.gov.vn', port=443): Max retries exceeded with url: /api/users/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024E1C78F4C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2024-11-19 10:40:29,859 - ERROR - L\u1ed7i khi \u0111\u0103ng nh\u1eadp: HTTPSConnectionPool(host='backend8181.bcy.gov.vn', port=443): Max retries exceeded with url: /api/users/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024E1C7C81C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2024-11-19 10:44:37,598 - INFO - pikepdf C++ to Python logger bridge initialized
2024-11-19 10:45:08,348 - WARNING - Forbidden (CSRF cookie not set.): /pdfdata/down/
2024-11-19 10:46:05,337 - INFO - D:\TTCSCN_NHOM38\backend\WEBPDF\webpdf\pdfdata\views.py changed, reloading.
2024-11-19 10:46:06,232 - INFO - pikepdf C++ to Python logger bridge initialized
2024-11-19 10:46:13,219 - INFO - D:\TTCSCN_NHOM38\backend\WEBPDF\webpdf\pdfdata\views.py changed, reloading.
2024-11-19 10:46:14,098 - INFO - pikepdf C++ to Python logger bridge initialized
2024-11-19 10:46:20,871 - INFO - \u0110ang x\u1eed lý trang 1 v\u1edbi 10 tài li\u1ec7u.
2024-11-19 10:46:22,927 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 1155 Q\u0110-HVM_0001.pdf__1731982582671: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:23,512 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 1036 TB-HVM_0001.pdf__1731895973266: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:25,873 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 1204 KH-HVM_0001.pdf__1731571914779: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:26,785 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file QD 1067.pdf__1731467490872: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:28,980 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh Khao sat y kien nguoi hoc sap tot nghiep.pdf__1731467490876: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:30,832 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh khao sat tinh hinh viec lam cua nguoi hoc sau tot nghiep 1 thang.pdf__1731467490880: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:32,734 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh khao sat tinh hinh viec lam cua nguoi hoc sau tot nghiep 1 nam.pdf__1731467490885: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:35,342 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh khao sat y kien cuu nguoi hoc.pdf__1731467490889: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:37,703 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh khao sat y kien nha tuyen dung ve chat luong dao tao cua Hoc vien.pdf__1731467490894: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:39,633 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh khao sat y kien can bo giang vien ve cac mat hoat dong cua Hoc vien.pdf__1731467490898: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:40,959 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh kiem tra, giam sat dam bao chat luong dao tao.pdf__1731467490902: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:42,873 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh cham thi ket thuc hoc phan.pdf__1731467490905: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:44,715 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 594 HVM-CTTC_0001.pdf__1731301514045: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:46,251 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file CÔNG V\u0102N TH\u1ef0C HÀNH TI\u1ebeT KI\u1ec6M CH\u1ed0NG LÃNG PHÍ.pdf__1731291563360: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:47,303 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file KH Triê\u0309n khai th\u01b0\u0323c hiê\u0323n Chi\u0309 thi\u0323 sô\u0301 27 nga\u0300y 25122023 vê\u0300 t\u0103ng c\u01b0\u01a1\u0300ng s\u01b0\u0323 la\u0303nh \u0111a\u0323o cau\u0309a \u0110a\u0309ng \u0111ô\u0301i v\u01a1\u0301i công ta\u0301c TH TK, CLP.pdf__1731291563365: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:47,521 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file phieu_trinh_van_ban_di.docx__1731312080188: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:48,741 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 05 TB-KHCN_0001.pdf__1731062750995: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:50,927 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file K\u1ebe HO\u1ea0CH BÁO T\u01af\u1edcNG 20.11.pdf__1730969947644: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:51,160 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file phieu_trinh_van_ban_di.docx__1730973131259: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:54,413 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file K\u1ebf ho\u1ea1ch VCRIS giai \u0111o\u1ea1n 2.pdf__1730969857635: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:54,631 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file phieu_trinh_van_ban_di.docx__1731042674084: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:55,902 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 1056 KH-HVM_0001.pdf__1730953618330: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:46:58,880 - INFO - \u0110ang x\u1eed lý trang 2 v\u1edbi 10 tài li\u1ec7u.
2024-11-19 10:47:00,274 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file K\u1ebf ho\u1ea1ch 20-11-2024.pdf__1730875344628: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:47:01,673 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Ph\u1ee5 l\u1ee5c I.pdf__1730875344632: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:47:03,024 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Ph\u1ee5 l\u1ee5c II.pdf__1730875344635: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:47:04,294 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Ph\u1ee5 l\u1ee5c III.pdf__1730875344638: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:47:05,543 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Ph\u1ee5 l\u1ee5c IV.pdf__1730875344641: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:47:06,802 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Ph\u1ee5 l\u1ee5c V.pdf__1730875344643: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:47:07,030 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file phieu_trinh_van_ban_di.docx__1730887344769: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:47:07,942 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file VBNB.HC_0001.pdf__1730863245559: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:48:11,854 - INFO - pikepdf C++ to Python logger bridge initialized
2024-11-19 10:48:21,137 - INFO - \u0110ang x\u1eed lý trang 1 v\u1edbi 10 tài li\u1ec7u.
2024-11-19 10:48:25,454 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 1155 Q\u0110-HVM_0001.pdf__1731982582671: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:48:26,448 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 1036 TB-HVM_0001.pdf__1731895973266: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:48:31,309 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 1204 KH-HVM_0001.pdf__1731571914779: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:48:32,688 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file QD 1067.pdf__1731467490872: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:06,407 - INFO - pikepdf C++ to Python logger bridge initialized
2024-11-19 10:54:16,950 - INFO - \u0110ang x\u1eed lý trang 1 v\u1edbi 10 tài li\u1ec7u.
2024-11-19 10:54:18,879 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 1155 Q\u0110-HVM_0001.pdf__1731982582671: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:19,590 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 1036 TB-HVM_0001.pdf__1731895973266: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:21,944 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 1204 KH-HVM_0001.pdf__1731571914779: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:22,793 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file QD 1067.pdf__1731467490872: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:24,964 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh Khao sat y kien nguoi hoc sap tot nghiep.pdf__1731467490876: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:26,804 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh khao sat tinh hinh viec lam cua nguoi hoc sau tot nghiep 1 thang.pdf__1731467490880: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:28,702 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh khao sat tinh hinh viec lam cua nguoi hoc sau tot nghiep 1 nam.pdf__1731467490885: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:31,295 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh khao sat y kien cuu nguoi hoc.pdf__1731467490889: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:33,584 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh khao sat y kien nha tuyen dung ve chat luong dao tao cua Hoc vien.pdf__1731467490894: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:35,496 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh khao sat y kien can bo giang vien ve cac mat hoat dong cua Hoc vien.pdf__1731467490898: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:36,815 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh kiem tra, giam sat dam bao chat luong dao tao.pdf__1731467490902: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:38,675 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh cham thi ket thuc hoc phan.pdf__1731467490905: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:40,516 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 594 HVM-CTTC_0001.pdf__1731301514045: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:42,004 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file CÔNG V\u0102N TH\u1ef0C HÀNH TI\u1ebeT KI\u1ec6M CH\u1ed0NG LÃNG PHÍ.pdf__1731291563360: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:43,043 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file KH Triê\u0309n khai th\u01b0\u0323c hiê\u0323n Chi\u0309 thi\u0323 sô\u0301 27 nga\u0300y 25122023 vê\u0300 t\u0103ng c\u01b0\u01a1\u0300ng s\u01b0\u0323 la\u0303nh \u0111a\u0323o cau\u0309a \u0110a\u0309ng \u0111ô\u0301i v\u01a1\u0301i công ta\u0301c TH TK, CLP.pdf__1731291563365: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:43,242 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file phieu_trinh_van_ban_di.docx__1731312080188: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:44,434 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 05 TB-KHCN_0001.pdf__1731062750995: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:46,584 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file K\u1ebe HO\u1ea0CH BÁO T\u01af\u1edcNG 20.11.pdf__1730969947644: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:46,802 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file phieu_trinh_van_ban_di.docx__1730973131259: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:50,065 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file K\u1ebf ho\u1ea1ch VCRIS giai \u0111o\u1ea1n 2.pdf__1730969857635: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:50,253 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file phieu_trinh_van_ban_di.docx__1731042674084: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:51,506 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 1056 KH-HVM_0001.pdf__1730953618330: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:54,372 - INFO - \u0110ang x\u1eed lý trang 2 v\u1edbi 10 tài li\u1ec7u.
2024-11-19 10:54:55,743 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file K\u1ebf ho\u1ea1ch 20-11-2024.pdf__1730875344628: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:57,114 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Ph\u1ee5 l\u1ee5c I.pdf__1730875344632: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:58,455 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Ph\u1ee5 l\u1ee5c II.pdf__1730875344635: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:54:59,694 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Ph\u1ee5 l\u1ee5c III.pdf__1730875344638: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:00,933 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Ph\u1ee5 l\u1ee5c IV.pdf__1730875344641: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:02,202 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Ph\u1ee5 l\u1ee5c V.pdf__1730875344643: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:02,402 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file phieu_trinh_van_ban_di.docx__1730887344769: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:03,324 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file VBNB.HC_0001.pdf__1730863245559: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:08,915 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Ke hoach TK nam 2024.pdf__1730797432979: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:09,124 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file phieu_trinh_van_ban_di.docx__1730861990887: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:11,456 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file K\u1ebf ho\u1ea1ch thi KTHP, HK2, 2023-2024 (KTXH). L\u1ea7n 2.pdf__1730343133524: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:11,645 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file phieu_trinh_van_ban_di.docx__1730363877602: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:12,925 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file M\u1eddi vi\u1ebft bài H\u1ed9i th\u1ea3o.pdf__1730191260799: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:13,124 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file phieu_trinh_van_ban_di.docx__1730192747657: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:14,883 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file CÔNG V\u0102N THAM GIA CU\u1ed8C THI SÁCH.pdf__1730169961434: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:17,616 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Th\u1ec3 l\u1ec7 cu\u1ed9c thi Tìm hi\u1ec3u sách.PDF__1730169961438: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:17,804 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file phieu_trinh_van_ban_di.docx__1730171891522: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:19,123 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Ban Phúc kh\u1ea3o CNTT - 2024 L2.pdf__1729847238056: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:19,314 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file phieu_trinh_van_ban_di.docx__1730078826587: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:21,265 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 1062 KH-HVM_0001.pdf__1729592178008: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:23,136 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file CV nhà tình ngh\u0129a, nhà \u0111\u1ed3ng \u0111\u1ed9i 2024.pdf__1729589647388: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:23,416 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file phieu_trinh_van_ban_di.docx__1729590008841: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:25,856 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Thông báo v\u1ec1 vi\u1ec7c hoàn thi\u1ec7n c\u01a1 s\u1edf d\u1eef li\u1ec7u Báo cáo T\u0110G CSGD (end1) - Copy.pdf__1729481301884: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:28,604 - INFO - \u0110ang x\u1eed lý trang 3 v\u1edbi 10 tài li\u1ec7u.
2024-11-19 10:55:28,833 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file DS Tr\u1ef1c T112024.docx__1729476412825: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:30,524 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file DS Tr\u1ef1c T112024.pdf__1729476413425: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:30,743 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file phieu_trinh_van_ban_di.docx__1729481455416: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:55:31,558 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Scan_0001397-KH \u0110UH.pdf__1729157577385: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:56:24,082 - INFO - pikepdf C++ to Python logger bridge initialized
2024-11-19 10:56:33,097 - INFO - \u0110ang x\u1eed lý trang 1 v\u1edbi 10 tài li\u1ec7u.
2024-11-19 10:56:35,006 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 1155 Q\u0110-HVM_0001.pdf__1731982582671: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:56:35,577 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 1036 TB-HVM_0001.pdf__1731895973266: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:56:37,930 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 1204 KH-HVM_0001.pdf__1731571914779: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:56:38,819 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file QD 1067.pdf__1731467490872: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:56:42,420 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh Khao sat y kien nguoi hoc sap tot nghiep.pdf__1731467490876: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:56:45,721 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh khao sat tinh hinh viec lam cua nguoi hoc sau tot nghiep 1 thang.pdf__1731467490880: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:56:47,838 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh khao sat tinh hinh viec lam cua nguoi hoc sau tot nghiep 1 nam.pdf__1731467490885: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:56:50,430 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh khao sat y kien cuu nguoi hoc.pdf__1731467490889: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:56:52,743 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh khao sat y kien nha tuyen dung ve chat luong dao tao cua Hoc vien.pdf__1731467490894: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:56:54,680 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh khao sat y kien can bo giang vien ve cac mat hoat dong cua Hoc vien.pdf__1731467490898: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:56:55,990 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh kiem tra, giam sat dam bao chat luong dao tao.pdf__1731467490902: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:56:57,831 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file Quy trinh cham thi ket thuc hoc phan.pdf__1731467490905: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:56:59,659 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 594 HVM-CTTC_0001.pdf__1731301514045: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:57:01,189 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file CÔNG V\u0102N TH\u1ef0C HÀNH TI\u1ebeT KI\u1ec6M CH\u1ed0NG LÃNG PHÍ.pdf__1731291563360: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:57:02,231 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file KH Triê\u0309n khai th\u01b0\u0323c hiê\u0323n Chi\u0309 thi\u0323 sô\u0301 27 nga\u0300y 25122023 vê\u0300 t\u0103ng c\u01b0\u01a1\u0300ng s\u01b0\u0323 la\u0303nh \u0111a\u0323o cau\u0309a \u0110a\u0309ng \u0111ô\u0301i v\u01a1\u0301i công ta\u0301c TH TK, CLP.pdf__1731291563365: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:57:02,441 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file phieu_trinh_van_ban_di.docx__1731312080188: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:57:03,647 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 05 TB-KHCN_0001.pdf__1731062750995: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:57:05,800 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file K\u1ebe HO\u1ea0CH BÁO T\u01af\u1edcNG 20.11.pdf__1730969947644: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:57:06,009 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file phieu_trinh_van_ban_di.docx__1730973131259: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:57:09,243 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file K\u1ebf ho\u1ea1ch VCRIS giai \u0111o\u1ea1n 2.pdf__1730969857635: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:57:09,470 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file phieu_trinh_van_ban_di.docx__1731042674084: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
2024-11-19 10:57:10,710 - ERROR - L\u1ed7i không xác \u0111\u1ecbnh khi l\u01b0u file 1056 KH-HVM_0001.pdf__1730953618330: (1146, "Table 'django.pdfdata_pdffile' doesn't exist")
